name: 'awsome-podcast-bot-action'
description: 'Github Action to help maintaining a directory of podcasts'
inputs:
  podcast-yaml-directory:
    description: 'directory where to store .yaml podcast description files'
    required: true
  podcast-json-directory:
    description: 'directory where to store .json enhanced podcast description files'
    required: true
  repo-token:
    description: 'Github personal access token to generate the podcast file'
    required: true
runs:
  using: 'node12'
  main: 'action/index.js'
